# Model Parameters
MODEL:
  # Model architecture
  ARCH: "bninception"
  # Flag to Freeze weights of base model
  FREEZE_BASE: True
  # Mode of freezing
  FREEZE_MODE: "partialbn"
  # Classes and their corresponding counts for the final linear layers
  NUM_CLASSES: { verb: 125, noun: 352 }
  # Aggregation type of the temporal windows for a trimmed segment
  AGG_TYPE: "avg"
  # Dropout probability for the fusion layer
  FUSION_DROPOUT: 0.5
  # Loss function to use
  LOSS_FN: "CrossEntropy"
  CHECKPOINT_DIR: "/path/to/save/model/weights"