# model parameters
model:
  arch: "bninception"
  use_attention: True
  freeze_base: True
  freeze_mode: "partialbn"
  num_classes: { verb: 125, noun: 352 }
  agg_type: "avg"
  fusion_dropout: 0.5
  loss_fn: "crossentropy"
  checkpoint_dir: "/media/data/tridiv/epic/tbn_weights/attention/seen"
