# model parameters
model:
  arch: "bninception"
  attention:
    enable: True
    attn_heads: 4
    attn_dropout: 0.5
    use_prior: True
    wt_loss: "kl"
    wt_decay: 1.0
    loss_reduction: "batchmean"
    use_contrast: True
    contrast_thresh: 0.1
    contrast_decay: 1.0
    use_entropy: True
    entropy_decay: 1
  resnet:
    depth: 101
  vgg:
    type: "16"
  freeze_base: True
  freeze_mode: "partialbn"
  num_classes: { verb: 125, noun: 352 }
  agg_type: "avg"
  fusion_dropout: 0.5
  loss_fn: "crossentropy"
  checkpoint_dir: "tbn_weights"
