# train parameters
train:
  enable: True
  annotation_file: "annotations/EPIC_train_action_labels.csv"
  vid_list: "data/train_split_seen.txt"
  batch_size: 12
  epochs: 30
  optim:
    type: "sgd"
    lr: 1e-2
    momentum: 0.9
    weight_decay: 0
    accumulator_step: 1
  scheduler:
    lr_steps: [20]
    lr_decay: 1e-1
  warmup:
    enable: False
    multiplier: 1
    epochs: 5
  clip_grad: 20
  num_segments: 3
  pre_trained: ""
