# Dataset Parameters
DATA:
  DATA_DIR: "/media/data/tridiv/epic"
  ANNOTATION_FILE: "/media/data/tridiv/epic_kitchens/annotations/EPIC_train_action_labels.csv"
  FRAME_DIR_PREFIX: "symlinks"
  READ_AUDIO_PICKLE: True
  AUDIO_DIR_PREFIX: "audio_pickle"
  DATASET: "epic"
  USE_RGB: True
  USE_FLOW: True
  USE_AUDIO: True
  OUT_DIR: ""
  IN_FPS: 60
  OUT_FPS: 30
  FRAME_FILE_EXT: "jpg"
  AUDIO_FILE_EXT: "wav"
  NUM_SEGMENTS: 3
  FLOW_WIN_LENGTH: 5
  SAMPLING_RATE: 24000
  AUDIO_LENGTH: 1.28
  RGB_MEAN: [0.408, 0.459, 0.502]
  RGB_STD: [1.0, 1.0, 1.0]
  FLOW_MEAN: [0.502]
  FLOW_STD: [1.0]
  TRAIN_SCALE_SIZE: 256
  TRAIN_CROP_SIZE: 224
  TEST_SCALE_SIZE: 256
  TEST_CROP_SIZE: 256
  TEST_TIMESTAMPS: "/media/data/tridiv/epic_kitchens/annotations/EPIC_test_s1_timestamps.csv"
# Model Parameters
MODEL:
  ARCH: "bninception"
  NUM_CLASSES: {
    verb: 127,
    noun: 352
  }
  AGG_TYPE: "avg"
  FUSION_DROPOUT: 0.5
  USE_SOFTMAX: True
  CHECKPOINT: ""
# Train Parameters
TRAIN:
  TRAIN_ENABLE: False
  VID_LIST: "./data/train_split.txt"
  OPTIM: "sgd"
  BATCH_SIZE: 22 
  EPOCHS: 25
  LR: 1e-2
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0
  LR_STEPS: [20, 40]
  LR_DECAY: 1e-6
  FREEZE_BASE: False
  FREEZE_FUSION: False
  NUM_SEGMENTS: 3
  PRE_TRAINED: ""
# Validation Parameters
VAL:
  VID_LIST: "./data/val_split.txt"
  BATCH_SIZE: 64
  PRE_TRAINED: ""
  TOPK: [1, 5]
  NUM_SEGMENTS: 3
  # Test Parameters
TEST:
  TEST_ENABLE: True
  VID_LIST: ""
  BATCH_SIZE: 64
  PRE_TRAINED: ""
  TOPK: [1, 5]
  NUM_SEGMENTS: 25
  SAVE_RESULTS:  True
  RESULTS_FILE: "seen.json"
  PRE_TRAINED: ""
# Misc
LOG_DIR: "./log"
NUM_WORKERS: 8 
NUM_GPUS: 1
