data:
  audio:
    audio_length: 2.1
    dir_prefix: audio_pickle
    dropout: 0.5
    enable: true
    file_ext: wav
    read_audio_pickle: true
    sampling_rate: 24000
    spec_type: stft
  dataset: epic
  flow:
    dir_prefix: links
    enable: false
    file_ext: jpg
    mean:
    - 0.502
    read_flow_pickle: false
    std:
    - 1.0
    win_length: 5
  manual_seed: 0
  rgb:
    dir_prefix: links
    enable: true
    file_ext: jpg
    mean:
    - 0.408
    - 0.459
    - 0.502
    std:
    - 1.0
    - 1.0
    - 1.0
  sampling: sync
  test_crop_size: 224
  test_scale_size: 256
  train_crop_size: 224
  train_scale_size: 256
  vid_fps: 60
data_dir: /media/data/tridiv/epic
gpu_ids: []
model:
  agg_type: avg
  arch: bninception
  attention:
    attn_dropout: 0.5
    attn_heads: 4
    contrast_decay: 0.25
    contrast_thresh: 0.1
    decay_step: 10
    enable: true
    entropy_decay: 0.25
    loss_reduction: batchmean
    prior_type: gaussian
    type: soft
    use_contrast: false
    use_entropy: true
    use_fixed: false
    use_gumbel: true
    use_prior: false
    use_pe: true
    wt_decay: 0.25
    wt_loss: kl
  checkpoint_dir: tbn_weights
  freeze_base: true
  freeze_mode: partialbn
  fusion_dropout: 0.5
  loss_fn: crossentropy
  num_classes:
    noun: 352
    verb: 125
  resnet:
    depth: 101
  vgg:
    type: '16'
num_workers: 8
out_dir: /media/data/tridiv/epic
test:
  annotation_file:
  - annotations/epic_train_val.csv
  batch_size: 1
  enable: true
  num_segments: 3
  pre_trained: /media/data/tridiv/epic/tbn_weights/audio_2.1_entropy_0.25_step_10/unseen/epic_tbn_bninception_RGB_Audio.pth
  results_file:
  - ''
  save_results: false
  topk:
  - 1
  - 5
  vid_list: data/val_split_unseen.txt