# Dataset Parameters
DATA:
  DATA_DIR: ""
  FRAME_DIR_PREFIX: ""
  AUDIO_DIR_PREFIX: ""
  DATASET: "epic"
  USE_RGB: True
  USE_FLOW: True
  USE_AUDIO: True
  OUT_DIR: ""
  IN_FPS: 60
  OUT_FPS: 30
  FRAME_FILE_EXT: "jpg"
  AUDIO_FILE_EXT: "wav"
  NUM_SEGMENTS: 3
  FLOW_WIN_LENGTH: 5
  SAMPLING_RATE: 24000
  AUDIO_LENGTH: 1.28
  RGB_MEAN: []
  RGB_STD: []
  FLOW_MEAN: []
  FLOW_STD: []
  AUDIO_MEAN: []
  FLOW_STD: []
  TRAIN_SCALE_SIZE: 256
  TRAIN_CROP_SIZE: 224
  TEST_SCALE_SIZE: 256
  TEST_CROP_SIZE: 256
  VIDEO_LIST: ""
# Model Parameters
MODEL:
  ARCH: "bninception"
  NUM_CLASSES: {
    verb: 127,
    noun: 325
  }
  CHECKPOINT: ""
# Train Parameters
TRAIN:
  TRAIN_ENABLE: True
  OPTIM: "sgd"
  BATCH_SIZE: 1
  EPOCHS: 25
  LR: 1e-4
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0
  LR_STEPS: [20, 40]
  LR_DECAY: 1e-6
  FREEZE_BASE: False
  FREEZE_FUSION: False
# Test Parameters
TEST:
  TEST_ENABLE: True
  BATCH_SIZE: 10
  PRE_TRAINED: ""
# Misc
LOG_DIR: ""
NUM_WORKERS: 8
NUM_GPUS: 1