DATA:
  DATA_DIR: ""
  FRAME_DIR_PREFIX: ""
  AUDIO_DIR_PREFIX: ""
  DATASET: "epic"
  USE_RGB: True
  USE_FLOW: True
  USE_AUDIO: True
  OUT_DIR: ""
  IN_FPS: 60
  OUT_FPS: 30
  FRAME_FILE_EXT: "jpg"
  AUDIO_FILE_EXT: "wav"
  FLOW_WIN_LENGTH: 5
  SAMPLING_RATE: 24000
  AUDIO_LENGTH: 1.28
  VIDEO_LIST: ""
MODEL:
  ARCH: "resnet101"
  NUM_CLASSES: [101]
  CHECKPOINT: ""
TRAIN:
  TRAIN_ENABLE: True
  OPTIM: "sgd"
  BATCH_SIZE: 1
  EPOCHS: 25
  LR: 1e-4
  LR_DECAY: 1e-6
  MOMENTUM: 0.9
  FREEZE: False
  PRE_TRAINED: ""
TEST:
  BATCH_SIZE: 10
  PRE_TRAINED: ""
RUN:
  LOG_DIR: ""
  NUM_WORKERS: 8
  NUM_GPUS: 1