# Dataset Parameters
DATA:
  DATA_DIR: "/media/data/tridiv"
  ANNOTATION_FILE: "/media/data/tridiv/epic_kitchens/annotations/EPIC_train_action_labels.csv"
  FRAME_DIR_PREFIX: "epic_symlinks"
  AUDIO_DIR_PREFIX: "epic_kitchens/EPIC_KITCHENS_2018/tbn/audio"
  DATASET: "epic"
  USE_RGB: True
  USE_FLOW: True
  USE_AUDIO: True
  OUT_DIR: ""
  IN_FPS: 60
  OUT_FPS: 30
  FRAME_FILE_EXT: "jpg"
  AUDIO_FILE_EXT: "wav"
  NUM_SEGMENTS: 3
  FLOW_WIN_LENGTH: 5
  SAMPLING_RATE: 24000
  AUDIO_LENGTH: 1.28
  RGB_MEAN: [0.408, 0.459, 0.502]
  RGB_STD: [1.0, 1.0, 1.0]
  FLOW_MEAN: [0.502]
  FLOW_STD: [1.0]
  TRAIN_SCALE_SIZE: 256
  TRAIN_CROP_SIZE: 224
  TEST_SCALE_SIZE: 256
  TEST_CROP_SIZE: 256
  VIDEO_LIST: ""
# Model Parameters
MODEL:
  ARCH: "bninception"
  NUM_CLASSES: {
    verb: 127,
    noun: 325
  }
  CHECKPOINT: ""
# Train Parameters
TRAIN:
  VID_LIST: "./train_split.txt"
  TRAIN_ENABLE: True
  OPTIM: "sgd"
  BATCH_SIZE: 1
  EPOCHS: 25
  LR: 1e-4
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0
  LR_STEPS: [20, 40]
  LR_DECAY: 1e-6
  FREEZE_BASE: False
  FREEZE_FUSION: False
# Test Parameters
TEST:
  VID_LIST: "./val_split.txt"
  TEST_ENABLE: True
  BATCH_SIZE: 10
  PRE_TRAINED: ""
# Misc
LOG_DIR: ""
NUM_WORKERS: 8
NUM_GPUS: 1