# Validation Parameters
VAL:
  # Flag to turn on/off validation
  VAL_ENABLE: True
  VID_LIST: "/path/to/video/list/to/process/for/validation"
  # Validation Batch size
  BATCH_SIZE: 6
  # Top k accuracies to compute
  TOPK: [1, 5]
  # Number of temporal segments to sample for each trimmed video segment
  NUM_SEGMENTS: 25